server:
  port: 8198

spring:
  application:
    name: hystrix-turbine-amqp-producer-application
  rabbitmq:
    host: localhost
    port: 5672
    username: springboot
    password: springboot

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/